site_name: Sudhandar Balakrishnan
site_description: AI consulting services
site_url: https://Sudhandar.github.io/blog/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - navigation.indexes
    - header.autohide
    - toc.permalink
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - tags

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      toc_depth: 2

nav:
  - Home: index.md
  - Consulting: consulting.md
  - Case Studies/Blogs:
      - Case Studies:
          - "The 15-Minute Weekly Report That Saved Millions in Regulatory Fines": blog/compliance-pipeline-blog-markdown.md
          - "Steal this LLM Workflow to book 60% more calls in your LinkedIn Outreach": blog/linkedin-outreach-overview.md
          - "Increasing Patient Condition Identification by 300% Using AI: A 6-Step Framework": blog/condition-identification-blog.md
      - Blogs:
          - "Turning Away Clients Because Google Drive Automation Can’t Handle 3× Capacity? Run This 5-Minute Audit": blog/drive-automation-pain-points.md
          - "Stop Second-Guessing Your AI: A Proven 4-Step Framework to Quantify Trust and Accelerate Deployments": blog/llm-eval-blog.md
          - "How to Debug Your RAG Before It's Too Late": blog/rag-retrieval-blog.md


extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://x.com/bsudhandar
      name: Follow me on X
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sudhandar/
      name: Connect with me on LinkedIn
  analytics:
    provider: google
    property: G-QBHPNWV21J
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - stylesheets/extra.css 